dependencies {
    implementation(project(":api"))
    compileOnly("it.unimi.dsi:fastutil:8.5.18")
}

// Check if the build was triggered with the 'liteBuild' property
val isLiteBuild = project.hasProperty("lite")

// Define path for generated sources. We don't use 'buildDirectory' here because it's overridden in the root script
// to fix the VSCode behavior.
val generatedSourcesDir = layout.projectDirectory.dir("build/generated/sources/constants/java")

// Create the task to generate the Java file
val generateConstants = tasks.register("generateBuildConstants") {
    // Explicitly define the outputs so Gradle can hook them automatically
    outputs.dir(generatedSourcesDir)
    
    doLast {
        val packageDir = generatedSourcesDir.dir("su/nightexpress/excellentclaims/core").asFile
        packageDir.mkdirs()
        
        val file = File(packageDir, "BuildConstants.java")
        val maxSomething = if (isLiteBuild) 10 else -1
        
        file.writeText("""
            package su.nightexpress.excellentclaims.core;
            
            // AUTO-GENERATED BY GRADLE. DO NOT EDIT.
            public final class BuildConstants {
                public static final boolean IS_LITE = $isLiteBuild;
                
                private BuildConstants() {}
            }
        """.trimIndent())
    }
}

// Tell Gradle to include the generated directory as a Java source set
sourceSets {
    main {
        java {
            srcDir(generateConstants)
        }
    }
}