package su.nightexpress.excellentclaims.api.claim;

public enum ClaimPermission {

    ALL,
    BUILDING,
    CONTAINERS,
    BLOCK_INTERACT,
    ENTITY_INTERACT,
    MANAGE_CLAIM,
    MANAGE_FLAGS,
    VIEW_MEMBERS,
    MANAGE_MEMBERS,
    ADD_MEMBERS,
    REMOVE_MEMBERS,
    PROMOTE_MEMBERS,
    DEMOTE_MEMBERS,
    MERGE_CLAIM,
    SEPARATE_CLAIM,
    RENAME_CLAIM,
    SET_CLAIM_DESCRIPTION,
    SET_CLAIM_SPAWN,
    SET_CLAIM_ICON,
    SET_CLAIM_PRIORITY,
    TRANSFER_CLAIM,
    REMOVE_CLAIM,
    TELEPORT

}
